application:
    name: auth-service
    port: 8081
    path: "/security"
    env: "development"
    log:
        file: "auth-service.log"
        level: info
        json: false

database:
    url: "mongodb://root:rootpassword@localhost:27017/videosmover_dev?retryWrites=true&w=majority"
    sync: true

authentication:
    algorithm: "HS256"
    secret: "dummySecret"
    accessExpirationMinutes: 15
    refreshExpirationDays: 7
    issuer: "auth-service"
    audience: "vm-services"
    salt: 10
