application:
    name: auth-service-dev
    port: 8081
    path: "/security"
    env: "development"
    log:
        file: "auth-service-dev.log"
        level: info
        json: false

database:
    url: "mongodb://root:rootpassword@localhost:27019/videosmover_dev?retryWrites=true&w=majority"
    sync: true

authentication:
    algorithm: "HS256"
    secret: "67uzoULtouBbSpwjVvzVQ5D1APKTc3i9"
    accessExpirationMinutes: 3
    refreshExpirationDays: 1
    refreshTokenName: refreshTokenDev
    issuer: auth-service-dev
    audience:
        - commander-dev
        - auth-service-dev
    salt: 10
